container:
  image: node:10.10
  cpu: 4
  memory: 4G

build_task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install

  build_script: yarn build

test_task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install

  test_script:
    - yarn test:coverage
