variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test
  - deploy

# Templates
.run_build_template:
  image: node:10.10
  script:
    - echo "Building widget..."
    - yarn
    - yarn build
    - echo "Preparing distribution version..."
    - rm -rf dist
    - mkdir dist
    - cp ./build/static/js/main.*.js ./dist/lightbot.js
  artifacts:
    paths:
      - ./dist

# Smart jobs
run_build:
  stage: test
  extends: .run_build_template
  only:
    - master

# Manual jobs
run_manual_build:
  stage: test
  extends: .run_build_template
  when: manual


# Docker build
run_docker_build:
  stage: deploy
  image: docker
  services:
    - docker:dind
  only:
    - master
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - printenv | grep -i "react_app_" >> .env.production
    - docker build -t ${CI_REGISTRY}/lightbase/lightbot-widget:latest -t ${CI_REGISTRY}/lightbase/lightbot-widget:$CI_COMMIT_SHA .
    - docker push ${CI_REGISTRY}/lightbase/lightbot-widget:latest
    - docker push ${CI_REGISTRY}/lightbase/lightbot-widget:$CI_COMMIT_SHA

